import React , {useState }from 'react'

function HavaDurumu() {

    const [havadurumu,setHavadurumu] = useState({
        "location": {
            "name": "Istanbul",
            "region": "Istanbul",
            "country": "Turkey",
            "lat": 41.02,
            "lon": 28.96,
            "tz_id": "Europe/Istanbul",
            "localtime_epoch": 1662106720,
            "localtime": "2022-09-02 11:18"
        },
        "forecast": {
            "forecastday": [
                {
                    "date": "2022-09-01",
                    "date_epoch": 1661990400,
                    "day": {
                        "maxtemp_c": 32.1,
                        "maxtemp_f": 89.8,
                        "mintemp_c": 24.6,
                        "mintemp_f": 76.3,
                        "avgtemp_c": 29.0,
                        "avgtemp_f": 84.2,
                        "maxwind_mph": 11.2,
                        "maxwind_kph": 18.0,
                        "totalprecip_mm": 0.0,
                        "totalprecip_in": 0.0,
                        "avgvis_km": 10.0,
                        "avgvis_miles": 6.0,
                        "avghumidity": 66.0,
                        "condition": {
                            "text": "Güneşli",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                            "code": 1000
                        },
                        "uv": 0.0
                    },
                    "astro": {
                        "sunrise": "06:30 AM",
                        "sunset": "07:37 PM",
                        "moonrise": "11:38 AM",
                        "moonset": "10:09 PM",
                        "moon_phase": "Waxing Crescent",
                        "moon_illumination": "35"
                    },
                    "hour": [
                        {
                            "time_epoch": 1661979600,
                            "time": "2022-09-01 00:00",
                            "temp_c": 25.4,
                            "temp_f": 77.7,
                            "is_day": 0,
                            "condition": {
                                "text": "Açık",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                                "code": 1000
                            },
                            "wind_mph": 8.1,
                            "wind_kph": 13.0,
                            "wind_degree": 8,
                            "wind_dir": "N",
                            "pressure_mb": 1010.0,
                            "pressure_in": 29.83,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "humidity": 74,
                            "cloud": 6,
                            "feelslike_c": 27.3,
                            "feelslike_f": 81.1,
                            "windchill_c": 25.4,
                            "windchill_f": 77.7,
                            "heatindex_c": 27.3,
                            "heatindex_f": 81.1,
                            "dewpoint_c": 20.5,
                            "dewpoint_f": 68.9,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 11.2,
                            "gust_kph": 18.0
                        },
                        {
                            "time_epoch": 1661983200,
                            "time": "2022-09-01 01:00",
                            "temp_c": 25.2,
                            "temp_f": 77.3,
                            "is_day": 0,
                            "condition": {
                                "text": "Açık",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                                "code": 1000
                            },
                            "wind_mph": 7.8,
                            "wind_kph": 12.6,
                            "wind_degree": 125,
                            "wind_dir": "SE",
                            "pressure_mb": 1010.0,
                            "pressure_in": 29.82,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "humidity": 75,
                            "cloud": 6,
                            "feelslike_c": 27.1,
                            "feelslike_f": 80.7,
                            "windchill_c": 25.2,
                            "windchill_f": 77.3,
                            "heatindex_c": 27.1,
                            "heatindex_f": 80.7,
                            "dewpoint_c": 20.4,
                            "dewpoint_f": 68.8,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 11.0,
                            "gust_kph": 17.6
                        },
                        {
                            "time_epoch": 1661986800,
                            "time": "2022-09-01 02:00",
                            "temp_c": 24.9,
                            "temp_f": 76.9,
                            "is_day": 0,
                            "condition": {
                                "text": "Açık",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                                "code": 1000
                            },
                            "wind_mph": 7.6,
                            "wind_kph": 12.2,
                            "wind_degree": 242,
                            "wind_dir": "WSW",
                            "pressure_mb": 1010.0,
                            "pressure_in": 29.82,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "humidity": 76,
                            "cloud": 6,
                            "feelslike_c": 26.8,
                            "feelslike_f": 80.3,
                            "windchill_c": 24.9,
                            "windchill_f": 76.9,
                            "heatindex_c": 26.8,
                            "heatindex_f": 80.3,
                            "dewpoint_c": 20.4,
                            "dewpoint_f": 68.7,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 10.7,
                            "gust_kph": 17.3
                        },
                        {
                            "time_epoch": 1661990400,
                            "time": "2022-09-01 03:00",
                            "temp_c": 24.7,
                            "temp_f": 76.5,
                            "is_day": 0,
                            "condition": {
                                "text": "Açık",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                                "code": 1000
                            },
                            "wind_mph": 7.4,
                            "wind_kph": 11.9,
                            "wind_degree": 359,
                            "wind_dir": "N",
                            "pressure_mb": 1010.0,
                            "pressure_in": 29.82,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "humidity": 77,
                            "cloud": 6,
                            "feelslike_c": 26.6,
                            "feelslike_f": 79.9,
                            "windchill_c": 24.7,
                            "windchill_f": 76.5,
                            "heatindex_c": 26.6,
                            "heatindex_f": 79.9,
                            "dewpoint_c": 20.3,
                            "dewpoint_f": 68.5,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 10.5,
                            "gust_kph": 16.9
                        },
                        {
                            "time_epoch": 1661994000,
                            "time": "2022-09-01 04:00",
                            "temp_c": 24.7,
                            "temp_f": 76.4,
                            "is_day": 0,
                            "condition": {
                                "text": "Açık",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                                "code": 1000
                            },
                            "wind_mph": 7.0,
                            "wind_kph": 11.3,
                            "wind_degree": 242,
                            "wind_dir": "WSW",
                            "pressure_mb": 1010.0,
                            "pressure_in": 29.82,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "humidity": 77,
                            "cloud": 8,
                            "feelslike_c": 26.6,
                            "feelslike_f": 79.8,
                            "windchill_c": 24.7,
                            "windchill_f": 76.4,
                            "heatindex_c": 26.6,
                            "heatindex_f": 79.8,
                            "dewpoint_c": 20.3,
                            "dewpoint_f": 68.5,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 9.9,
                            "gust_kph": 16.0
                        },
                        {
                            "time_epoch": 1661997600,
                            "time": "2022-09-01 05:00",
                            "temp_c": 24.6,
                            "temp_f": 76.3,
                            "is_day": 0,
                            "condition": {
                                "text": "Açık",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                                "code": 1000
                            },
                            "wind_mph": 6.6,
                            "wind_kph": 10.7,
                            "wind_degree": 124,
                            "wind_dir": "SE",
                            "pressure_mb": 1010.0,
                            "pressure_in": 29.82,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "humidity": 77,
                            "cloud": 9,
                            "feelslike_c": 26.5,
                            "feelslike_f": 79.8,
                            "windchill_c": 24.6,
                            "windchill_f": 76.3,
                            "heatindex_c": 26.5,
                            "heatindex_f": 79.8,
                            "dewpoint_c": 20.3,
                            "dewpoint_f": 68.5,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 9.3,
                            "gust_kph": 15.0
                        },
                        {
                            "time_epoch": 1662001200,
                            "time": "2022-09-01 06:00",
                            "temp_c": 24.6,
                            "temp_f": 76.3,
                            "is_day": 0,
                            "condition": {
                                "text": "Açık",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                                "code": 1000
                            },
                            "wind_mph": 6.3,
                            "wind_kph": 10.1,
                            "wind_degree": 6,
                            "wind_dir": "N",
                            "pressure_mb": 1010.0,
                            "pressure_in": 29.82,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "humidity": 77,
                            "cloud": 10,
                            "feelslike_c": 26.5,
                            "feelslike_f": 79.7,
                            "windchill_c": 24.6,
                            "windchill_f": 76.3,
                            "heatindex_c": 26.5,
                            "heatindex_f": 79.7,
                            "dewpoint_c": 20.3,
                            "dewpoint_f": 68.5,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 8.7,
                            "gust_kph": 14.0
                        },
                        {
                            "time_epoch": 1662004800,
                            "time": "2022-09-01 07:00",
                            "temp_c": 25.5,
                            "temp_f": 77.8,
                            "is_day": 1,
                            "condition": {
                                "text": "Güneşli",
                                "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                                "code": 1000
                            },
                            "wind_mph": 6.0,
                            "wind_kph": 9.6,
                            "wind_degree": 13,
                            "wind_dir": "NNE",
                            "pressure_mb": 1010.0,
                            "pressure_in": 29.82,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "humidity": 72,
                            "cloud": 9,
                            "feelslike_c": 27.3,
                            "feelslike_f": 81.1,
                            "windchill_c": 25.5,
                            "windchill_f": 77.8,
                            "heatindex_c": 27.3,
                            "heatindex_f": 81.1,
                            "dewpoint_c": 19.9,
                            "dewpoint_f": 67.9,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 8.1,
                            "gust_kph": 13.0
                        },
                        {
                            "time_epoch": 1662008400,
                            "time": "2022-09-01 08:00",
                            "temp_c": 26.3,
                            "temp_f": 79.4,
                            "is_day": 1,
                            "condition": {
                                "text": "Güneşli",
                                "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                                "code": 1000
                            },
                            "wind_mph": 5.7,
                            "wind_kph": 9.1,
                            "wind_degree": 21,
                            "wind_dir": "NNE",
                            "pressure_mb": 1010.0,
                            "pressure_in": 29.82,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "humidity": 67,
                            "cloud": 9,
                            "feelslike_c": 28.0,
                            "feelslike_f": 82.5,
                            "windchill_c": 26.3,
                            "windchill_f": 79.4,
                            "heatindex_c": 28.0,
                            "heatindex_f": 82.5,
                            "dewpoint_c": 19.6,
                            "dewpoint_f": 67.2,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 7.4,
                            "gust_kph": 11.9
                        },
                        {
                            "time_epoch": 1662012000,
                            "time": "2022-09-01 09:00",
                            "temp_c": 27.2,
                            "temp_f": 81.0,
                            "is_day": 1,
                            "condition": {
                                "text": "Güneşli",
                                "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                                "code": 1000
                            },
                            "wind_mph": 5.4,
                            "wind_kph": 8.6,
                            "wind_degree": 28,
                            "wind_dir": "NNE",
                            "pressure_mb": 1010.0,
                            "pressure_in": 29.83,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "humidity": 62,
                            "cloud": 8,
                            "feelslike_c": 28.8,
                            "feelslike_f": 83.8,
                            "windchill_c": 27.2,
                            "windchill_f": 81.0,
                            "heatindex_c": 28.8,
                            "heatindex_f": 83.8,
                            "dewpoint_c": 19.2,
                            "dewpoint_f": 66.6,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 6.7,
                            "gust_kph": 10.8
                        },
                        {
                            "time_epoch": 1662015600,
                            "time": "2022-09-01 10:00",
                            "temp_c": 28.7,
                            "temp_f": 83.7,
                            "is_day": 1,
                            "condition": {
                                "text": "Güneşli",
                                "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                                "code": 1000
                            },
                            "wind_mph": 4.1,
                            "wind_kph": 6.6,
                            "wind_degree": 137,
                            "wind_dir": "SE",
                            "pressure_mb": 1010.0,
                            "pressure_in": 29.83,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "humidity": 59,
                            "cloud": 10,
                            "feelslike_c": 31.0,
                            "feelslike_f": 87.8,
                            "windchill_c": 28.7,
                            "windchill_f": 83.7,
                            "heatindex_c": 31.0,
                            "heatindex_f": 87.8,
                            "dewpoint_c": 19.9,
                            "dewpoint_f": 67.9,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 5.1,
                            "gust_kph": 8.2
                        },
                        {
                            "time_epoch": 1662019200,
                            "time": "2022-09-01 11:00",
                            "temp_c": 30.3,
                            "temp_f": 86.5,
                            "is_day": 1,
                            "condition": {
                                "text": "Güneşli",
                                "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                                "code": 1000
                            },
                            "wind_mph": 2.8,
                            "wind_kph": 4.6,
                            "wind_degree": 245,
                            "wind_dir": "WSW",
                            "pressure_mb": 1010.0,
                            "pressure_in": 29.82,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "humidity": 57,
                            "cloud": 11,
                            "feelslike_c": 33.2,
                            "feelslike_f": 91.8,
                            "windchill_c": 30.3,
                            "windchill_f": 86.5,
                            "heatindex_c": 33.2,
                            "heatindex_f": 91.8,
                            "dewpoint_c": 20.7,
                            "dewpoint_f": 69.2,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 3.4,
                            "gust_kph": 5.5
                        },
                        {
                            "time_epoch": 1662022800,
                            "time": "2022-09-01 12:00",
                            "temp_c": 31.8,
                            "temp_f": 89.2,
                            "is_day": 1,
                            "condition": {
                                "text": "Güneşli",
                                "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                                "code": 1000
                            },
                            "wind_mph": 1.6,
                            "wind_kph": 2.5,
                            "wind_degree": 353,
                            "wind_dir": "N",
                            "pressure_mb": 1010.0,
                            "pressure_in": 29.82,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "humidity": 54,
                            "cloud": 13,
                            "feelslike_c": 35.4,
                            "feelslike_f": 95.7,
                            "windchill_c": 31.8,
                            "windchill_f": 89.2,
                            "heatindex_c": 35.4,
                            "heatindex_f": 95.7,
                            "dewpoint_c": 21.4,
                            "dewpoint_f": 70.5,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 1.8,
                            "gust_kph": 2.9
                        },
                        {
                            "time_epoch": 1662026400,
                            "time": "2022-09-01 13:00",
                            "temp_c": 31.9,
                            "temp_f": 89.4,
                            "is_day": 1,
                            "condition": {
                                "text": "Güneşli",
                                "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                                "code": 1000
                            },
                            "wind_mph": 2.7,
                            "wind_kph": 4.3,
                            "wind_degree": 241,
                            "wind_dir": "WSW",
                            "pressure_mb": 1010.0,
                            "pressure_in": 29.81,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "humidity": 54,
                            "cloud": 13,
                            "feelslike_c": 35.5,
                            "feelslike_f": 96.0,
                            "windchill_c": 31.9,
                            "windchill_f": 89.4,
                            "heatindex_c": 35.5,
                            "heatindex_f": 96.0,
                            "dewpoint_c": 21.4,
                            "dewpoint_f": 70.5,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 3.1,
                            "gust_kph": 4.9
                        },
                        {
                            "time_epoch": 1662030000,
                            "time": "2022-09-01 14:00",
                            "temp_c": 32.0,
                            "temp_f": 89.6,
                            "is_day": 1,
                            "condition": {
                                "text": "Güneşli",
                                "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                                "code": 1000
                            },
                            "wind_mph": 3.8,
                            "wind_kph": 6.1,
                            "wind_degree": 129,
                            "wind_dir": "SE",
                            "pressure_mb": 1009.0,
                            "pressure_in": 29.81,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "humidity": 54,
                            "cloud": 13,
                            "feelslike_c": 35.7,
                            "feelslike_f": 96.2,
                            "windchill_c": 32.0,
                            "windchill_f": 89.6,
                            "heatindex_c": 35.7,
                            "heatindex_f": 96.2,
                            "dewpoint_c": 21.4,
                            "dewpoint_f": 70.5,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 4.3,
                            "gust_kph": 7.0
                        },
                        {
                            "time_epoch": 1662033600,
                            "time": "2022-09-01 15:00",
                            "temp_c": 32.1,
                            "temp_f": 89.8,
                            "is_day": 1,
                            "condition": {
                                "text": "Güneşli",
                                "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                                "code": 1000
                            },
                            "wind_mph": 4.9,
                            "wind_kph": 7.9,
                            "wind_degree": 16,
                            "wind_dir": "NNE",
                            "pressure_mb": 1009.0,
                            "pressure_in": 29.8,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "humidity": 53,
                            "cloud": 13,
                            "feelslike_c": 35.8,
                            "feelslike_f": 96.4,
                            "windchill_c": 32.1,
                            "windchill_f": 89.8,
                            "heatindex_c": 35.8,
                            "heatindex_f": 96.4,
                            "dewpoint_c": 21.4,
                            "dewpoint_f": 70.5,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 5.6,
                            "gust_kph": 9.0
                        },
                        {
                            "time_epoch": 1662037200,
                            "time": "2022-09-01 16:00",
                            "temp_c": 31.1,
                            "temp_f": 88.0,
                            "is_day": 1,
                            "condition": {
                                "text": "Güneşli",
                                "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                                "code": 1000
                            },
                            "wind_mph": 7.0,
                            "wind_kph": 11.3,
                            "wind_degree": 19,
                            "wind_dir": "NNE",
                            "pressure_mb": 1009.0,
                            "pressure_in": 29.8,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "humidity": 55,
                            "cloud": 12,
                            "feelslike_c": 34.4,
                            "feelslike_f": 93.9,
                            "windchill_c": 31.1,
                            "windchill_f": 88.0,
                            "heatindex_c": 34.4,
                            "heatindex_f": 93.9,
                            "dewpoint_c": 21.1,
                            "dewpoint_f": 69.9,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 8.1,
                            "gust_kph": 13.0
                        },
                        {
                            "time_epoch": 1662040800,
                            "time": "2022-09-01 17:00",
                            "temp_c": 30.2,
                            "temp_f": 86.3,
                            "is_day": 1,
                            "condition": {
                                "text": "Güneşli",
                                "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                                "code": 1000
                            },
                            "wind_mph": 9.1,
                            "wind_kph": 14.6,
                            "wind_degree": 23,
                            "wind_dir": "NNE",
                            "pressure_mb": 1009.0,
                            "pressure_in": 29.8,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "humidity": 57,
                            "cloud": 10,
                            "feelslike_c": 32.9,
                            "feelslike_f": 91.3,
                            "windchill_c": 30.2,
                            "windchill_f": 86.3,
                            "heatindex_c": 32.9,
                            "heatindex_f": 91.3,
                            "dewpoint_c": 20.7,
                            "dewpoint_f": 69.3,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 10.5,
                            "gust_kph": 16.9
                        },
                        {
                            "time_epoch": 1662044400,
                            "time": "2022-09-01 18:00",
                            "temp_c": 29.2,
                            "temp_f": 84.6,
                            "is_day": 1,
                            "condition": {
                                "text": "Güneşli",
                                "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                                "code": 1000
                            },
                            "wind_mph": 11.2,
                            "wind_kph": 18.0,
                            "wind_degree": 26,
                            "wind_dir": "NNE",
                            "pressure_mb": 1009.0,
                            "pressure_in": 29.8,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "humidity": 59,
                            "cloud": 9,
                            "feelslike_c": 31.5,
                            "feelslike_f": 88.7,
                            "windchill_c": 29.2,
                            "windchill_f": 84.6,
                            "heatindex_c": 31.5,
                            "heatindex_f": 88.7,
                            "dewpoint_c": 20.4,
                            "dewpoint_f": 68.7,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 13.0,
                            "gust_kph": 20.9
                        },
                        {
                            "time_epoch": 1662048000,
                            "time": "2022-09-01 19:00",
                            "temp_c": 28.2,
                            "temp_f": 82.7,
                            "is_day": 1,
                            "condition": {
                                "text": "Güneşli",
                                "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                                "code": 1000
                            },
                            "wind_mph": 11.1,
                            "wind_kph": 17.9,
                            "wind_degree": 31,
                            "wind_dir": "NNE",
                            "pressure_mb": 1010.0,
                            "pressure_in": 29.81,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "humidity": 64,
                            "cloud": 9,
                            "feelslike_c": 30.4,
                            "feelslike_f": 86.7,
                            "windchill_c": 28.2,
                            "windchill_f": 82.7,
                            "heatindex_c": 30.4,
                            "heatindex_f": 86.7,
                            "dewpoint_c": 20.7,
                            "dewpoint_f": 69.2,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 13.4,
                            "gust_kph": 21.6
                        },
                        {
                            "time_epoch": 1662051600,
                            "time": "2022-09-01 20:00",
                            "temp_c": 27.1,
                            "temp_f": 80.8,
                            "is_day": 0,
                            "condition": {
                                "text": "Açık",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                                "code": 1000
                            },
                            "wind_mph": 11.0,
                            "wind_kph": 17.8,
                            "wind_degree": 36,
                            "wind_dir": "NE",
                            "pressure_mb": 1010.0,
                            "pressure_in": 29.83,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "humidity": 69,
                            "cloud": 9,
                            "feelslike_c": 29.3,
                            "feelslike_f": 84.7,
                            "windchill_c": 27.1,
                            "windchill_f": 80.8,
                            "heatindex_c": 29.3,
                            "heatindex_f": 84.7,
                            "dewpoint_c": 20.9,
                            "dewpoint_f": 69.7,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 13.9,
                            "gust_kph": 22.3
                        },
                        {
                            "time_epoch": 1662055200,
                            "time": "2022-09-01 21:00",
                            "temp_c": 26.1,
                            "temp_f": 79.0,
                            "is_day": 0,
                            "condition": {
                                "text": "Açık",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                                "code": 1000
                            },
                            "wind_mph": 11.0,
                            "wind_kph": 17.6,
                            "wind_degree": 42,
                            "wind_dir": "NE",
                            "pressure_mb": 1011.0,
                            "pressure_in": 29.84,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "humidity": 74,
                            "cloud": 10,
                            "feelslike_c": 28.2,
                            "feelslike_f": 82.8,
                            "windchill_c": 26.1,
                            "windchill_f": 79.0,
                            "heatindex_c": 28.2,
                            "heatindex_f": 82.8,
                            "dewpoint_c": 21.2,
                            "dewpoint_f": 70.2,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 14.3,
                            "gust_kph": 23.0
                        },
                        {
                            "time_epoch": 1662058800,
                            "time": "2022-09-01 22:00",
                            "temp_c": 25.8,
                            "temp_f": 78.5,
                            "is_day": 0,
                            "condition": {
                                "text": "Açık",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                                "code": 1000
                            },
                            "wind_mph": 10.4,
                            "wind_kph": 16.7,
                            "wind_degree": 43,
                            "wind_dir": "NE",
                            "pressure_mb": 1010.0,
                            "pressure_in": 29.84,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "humidity": 75,
                            "cloud": 9,
                            "feelslike_c": 27.9,
                            "feelslike_f": 82.2,
                            "windchill_c": 25.8,
                            "windchill_f": 78.5,
                            "heatindex_c": 27.9,
                            "heatindex_f": 82.2,
                            "dewpoint_c": 21.0,
                            "dewpoint_f": 69.8,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 13.8,
                            "gust_kph": 22.2
                        },
                        {
                            "time_epoch": 1662062400,
                            "time": "2022-09-01 23:00",
                            "temp_c": 25.6,
                            "temp_f": 78.0,
                            "is_day": 0,
                            "condition": {
                                "text": "Açık",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                                "code": 1000
                            },
                            "wind_mph": 9.8,
                            "wind_kph": 15.7,
                            "wind_degree": 44,
                            "wind_dir": "NE",
                            "pressure_mb": 1010.0,
                            "pressure_in": 29.84,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "humidity": 75,
                            "cloud": 8,
                            "feelslike_c": 27.5,
                            "feelslike_f": 81.6,
                            "windchill_c": 25.6,
                            "windchill_f": 78.0,
                            "heatindex_c": 27.5,
                            "heatindex_f": 81.6,
                            "dewpoint_c": 20.8,
                            "dewpoint_f": 69.4,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 13.3,
                            "gust_kph": 21.4
                        }
                    ]
                }
            ]
        }
    });


  return (
    <div>HavaDurumu</div>
  )
}

export default HavaDurumu